<template>
    <div class="paper print">
        <div class="logo">
            <img src="@/assets/img/admin-logo.svg" alt="Company Logo">
        </div>
        <h1>Tourist Arrival Report</h1>
        <p>Report for tourists arrived between {{displayDates}}</p>
        <table>
            <thead>
                <th>#</th>
                <th>Tourist Name</th>
                <th>From</th>
                <th>Arrived on</th>
            </thead>
            <tbody>
                <tr v-if="tourists == 'loading...'">
                    <td colspan="4" style="text-align: center"> <i class="material-icons">info</i> Data is loading ...</td>
                </tr>
                <tr v-else-if="tourists.length < 1">
                    <td colspan="4" style="text-align: center"><i class="material-icons">info</i> No tourists arived at {{ displayDates }}</td>
                </tr>
                <tr v-else v-for="(tourist, i) in tourists" :key="tourist.id">
                    <td>{{ i+1 }}</td>
                    <td>{{ tourist.first_name }} {{ tourist.last_name }}</td>
                    <td>{{ tourist.location }}</td>
                    <td>{{ moment(tourist.created_at).format('MMMM DD, YYYY hh:mm:ss A') }}</td>
                </tr>
            </tbody>
        </table>
        <p>This report is generated by the <b>OTIMRS</b> on {{ moment().format('MMMM DD, YYYY hh:mm:ss A') }}</p>
    </div>
    <div class="loading-screen no-print">
        <img src="@/assets/img/admin-logo.svg" alt="">
        <h3>Generating report ...</h3>
        <img src="@/assets/img/loading.svg" alt="Loading" class="loading">
    </div>
</template>

<script setup>
import moment from 'moment';
import { makeRequest } from '@/plugins/axios';
import { computed, onMounted, ref, nextTick  } from 'vue';

const tourists = ref('loading...');

const date_range = ref([]);
const query = new URLSearchParams(window.location.search);
const from = query.get('from');
const to = query.get('to');

if (from && to) {
    date_range.value = [new Date(from), new Date(to)];
} else {
    date_range.value = [new Date(), new Date()];
}

function getData() {
    tourists.value = 'loading...';
    makeRequest.get(`/arrivals?from=${moment(date_range.value[0]).format('YYYY-MM-DD')}&to=${moment(date_range.value[1]).format('YYYY-MM-DD')}`).then(res => {
        if (res.data.success) {
            console.log('Requested!');

            tourists.value = res.data.data;

            nextTick( () => {
                setTimeout(() => {
                    window.print();
                    window.close();
                }, 500);
            } )
        } else {
            alert('Failed to print!');
            window.close();
        }
    })
}

const displayDates = computed(() => {

// console.log(date_range.value[0], date_range.value[1])
if (date_range.value[0] == date_range.value[1]) return moment(date_range.value[0]).format('MMMM DD, YYYY');

return date_range.value ? moment(date_range.value[0]).format('MMMM DD, YYYY') + ' - ' + moment(date_range.value[1]).format('MMMM DD, YYYY')  : 'Today';
});


onMounted(() => {
    // make request using makeRequest from plugins/axios and get /tourists and put it in a reference
    getData();
})
</script>

<style scoped lang="scss">

.loading-screen {
    display: flex;
    height: 100vh;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    h3 {
        font-weight: normal;
        margin-top: 30px;
        opacity: 0.7;
    }
    position: fixed;
    inset: 0;
    z-index: 9;
    background-color: white;

    img {
        width: 300px;

        &.loading {
            width: 70px;
            margin-top: 30px;
        }
    }
}

// .loading-screen {
//     display: none;
// }



    
.paper {
    text-align: center;
    padding: 15px;
    font-size: 16px;
    display: block;

    h1 {
        font-size: 1.4rem;
        margin-bottom: 20px;
    }

    img {
        width: 150px;
        margin: 20px;
        margin-top: 0;
    }

    p {
        color: rgba(0, 0, 0, 0.541);
    }

    table {
        margin: 30px auto;
        width: 100%;
        border-collapse: collapse;
        
        th {
            background-color: #2A9DF2;
            color: white;
        }

        tr:nth-child(even) {
            background-color: rgba(0, 0, 0, 0.083);
        }

        th, td {
            padding: 15px;
            
        }
    }

    b {
        color: #2A9DF2;
    }
}

// .print {
//     display: none;
// }

@media print {
    .no-print {
        display: none !important;
    }

    .print {
        display: block !important;
    }
}


</style>